import { Activity, CheckCircle2, HeartPulse, Radio } from 'lucide-react';
import { Navigate } from 'react-router-dom';
import { LoginForm } from '../components/LoginForm';
import { useAuthStore } from '../store/authStore';

export function LoginPage() {
  const authenticated = useAuthStore((state) => state.isAuthenticated());
  if (authenticated) return <Navigate to="/dashboard" replace />;
  return <main className="min-h-screen bg-navy-900 lg:grid lg:grid-cols-[1.08fr_0.92fr]">
    <section className="relative hidden overflow-hidden p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-20 -top-20 h-96 w-96 rounded-full bg-aqua-500/20 blur-3xl" /><div className="relative flex items-center gap-3"><div className="rounded-2xl bg-white/10 p-3 ring-1 ring-white/20"><HeartPulse /></div><div><p className="font-semibold">Hastane Operasyon Merkezi</p><p className="text-xs text-slate-300">Agentic AI destekli randevu yönetimi</p></div></div><div className="relative max-w-xl"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-aqua-100">Canlı kontrol kulesi</p><h1 className="text-5xl font-semibold leading-tight">Her çağrı, her randevu, tek güvenli görünümde.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-300">Yapay zekâ destekli çağrı akışlarını, hasta randevularını ve servis sağlığını gerçek zamanlı izleyin.</p><div className="mt-10 grid grid-cols-3 gap-3">{[[Activity, 'Anlık metrikler'], [Radio, 'Canlı olaylar'], [CheckCircle2, 'Uçtan uca izleme']].map(([Icon, text]) => { const ItemIcon = Icon as typeof Activity; return <div key={String(text)} className="rounded-2xl bg-white/5 p-4 ring-1 ring-white/10"><ItemIcon className="mb-3 text-aqua-100" size={20} /><p className="text-sm">{String(text)}</p></div>; })}</div></div><p className="relative text-xs text-slate-400">Kişisel sağlık verileri güvenli ve maskeli gösterilir.</p></section>
    <section className="flex min-h-screen items-center justify-center bg-slate-50 px-5 py-10"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><HeartPulse className="text-aqua-600" /><p className="mt-2 font-semibold text-navy-900">Hastane Operasyon Merkezi</p></div><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-panel sm:p-9"><p className="text-sm font-semibold text-aqua-700">Operasyon paneli</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-navy-900">Tekrar hoş geldiniz</h2><p className="mb-8 mt-2 text-sm leading-6 text-slate-500">Yetkili kurum hesabınızla devam edin.</p><LoginForm /><div className="mt-6 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500"><strong>Demo:</strong> Formdaki örnek hesapla giriş yapabilirsiniz.</div></div></div></section>
  </main>;
}
